### ISSUE TITLE
intra process test is flaky

### ISSUE THREAD

**Issue by wjwwood** [ros2/system_tests#39]
http://ci.ros2.org/job/ros2_batch_ci_linux/297/testReport/junit/(root)/test_intra_process_within_one_node/nominal_usage/

It has failed a few times on the CI, but locally I cannot reproduce it. I think we can just add more re-try loops, but first I want to understand why two is not enough.

**Comment by dirk-thomas** [comment]
This seems to pass now: http://ci.ros2.org/job/ci_linux/1251/testReport/(root)/test_intra_process_within_one_node/

But all tests report the same name and should include the rmw implementation name.

**Comment by jacquelinekay** [comment]
I opened ros2/system_tests#116 to address the rmw implementation in the label.

**Comment by wjwwood** [comment]
Thanks @jacquelinekay.
