### ISSUE TITLE
building test_communication with other RMWs

### ISSUE THREAD

**Issue by adamsj-oci** [ros2/system_tests#407]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source
- Version or commit hash:
  - 68c495 (master)
- DDS implementation:
  - apparently only FAST-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

How does this work with `colcon`? I tried building with `RMW_IMPLEMENTATION` (for something other than `rmw_fastrtps_cpp` but that doesn't seem to affect [this line](https://github.com/ros2/system_tests/blob/eloquent/test_communication/CMakeLists.txt#L73) which is how I assume I run `test_communication` against other RMWs.

More precisely:
```
$ colcon list
...
rmw_cyclonedds_cpp

$ RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
$ colcon build --symlink-install --packages-up-to test_communication

```

#### Expected behavior
```
$ grep -i cyclone log/latest_build/test_communication/*
(cyclone matches in logs)
```

#### Actual behavior
no matches

#### Additional information
My assumption is that log matches would indicate cyclone tests were built as indicated by the line in the CMakeLists.txt

**Comment by adamsj-oci** [comment]
Bad bug! I didn't need `$ RMW_IMPLEMENTATION=rmw_cyclonedds_cpp` but I didn't forget to source the `local_setup.bash`. I had previously run `$ colcon list` from the command line and `$ colcon build ...` in a script which didn't have the same environment sourced. Once I fixed the environment, then I started to see output in the build logs.

**Comment by tfoote** [comment]
Thanks for the follow up. Glad it's working.
