### ISSUE TITLE
How to run test with my package

### ISSUE THREAD

**Issue by k2kite-megankim** [ros2/system_tests#461]
How can I use this system_tests for testing my package?
Please let me know how I can set the test directory.
Also, I want to set the parameter INITIAL_PARAMS_RCLCPP and INITIAL_PARAMS_RCLPY
Is there any guide or something?TT

## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by clalancette** [comment]
For questions like this, please ask them on https://answers.ros.org.  That way all of the questions and answers are in one searchable place.  I'm going to close this one out for now.
