### ISSUE TITLE
test_rclcpp.TestTwoExecutablesAfterShutdown.test_node_name flaky

### ISSUE THREAD

**Issue by tfoote** [ros2/system_tests#464]
## Bug report

https://github.com/ros2/rclcpp/issues/1552
**Required Info:**

- Operating System:
  - OSX
- Installation type:
  - nightly_osx_repeated
- Version or commit hash:
  - nightly
- DDS implementation:
  - The errors appear for tests between cyclonedds and fastrtps_cpp
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

This failed on the nightly CI run:

https://ci.ros2.org/job/nightly_osx_repeated/2275/testReport/

As well as about 2 weeks ago:

https://ci.ros2.org/job/nightly_osx_repeated/2257/testReport/

![Screenshot from 2021-03-08 14-28-49](https://user-images.githubusercontent.com/447804/110390774-572d7000-801b-11eb-8b63-97b895080b0e.png)

#### Expected behavior

Tests Pass

#### Actual behavior

```
Traceback (most recent call last):
  File "/Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/build/test_rclcpp/test_node_name__rmw_cyclonedds_cpp__rmw_fastrtps_cpp_.py", line 75, in test_node_name
    launch_testing.asserts.assertExitCodes(
  File "/Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/install/launch_testing/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py", line 62, in assertExitCodes
    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(
AssertionError: Proc node_with_name-1 exited with code -6
```

#### Additional information

In both cases this failure is also correlated with instances of: https://github.com/ros2/rclcpp/issues/1552 and not other failures.

**Comment by clalancette** [comment]
Since we are no longer running the macOS jobs nightly, I'm going to close this out.
