### ISSUE TITLE
👩‍🌾 test_communication compilation failing nightly coverage builds

### ISSUE THREAD

**Issue by chapulina** [ros2/system_tests#484]
## Bug report

**Required Info:**

- Operating System: Ubuntu Focal
  - 
- Installation type: Source, 
  - 
- Version or commit hash: master
  - 
- DDS implementation: Default
  - 

#### Steps to reproduce issue

Run nightly coverage jobs:

https://ci.ros2.org/job/nightly_linux_coverage/

#### Expected behavior

All packages build

#### Actual behavior

`test_communication` fails to build and brings down the entire job. This has happened for the past 2 nightlies.

#### Additional information

I originally thought it was a spurious failure, but both nightlies failed at the exact same spot:

```
02:27:08 [ 44%] Building CXX object CMakeFiles/test_subscriber_cpp.dir/test/test_subscriber.cpp.o
02:27:08 c++: fatal error: Killed signal terminated program cc1plus
02:27:08 compilation terminated.
02:27:08 make[2]: *** [CMakeFiles/test_subscriber_cpp.dir/build.make:63: CMakeFiles/test_subscriber_cpp.dir/test/test_subscriber.cpp.o] Error 1
02:27:08 make[1]: *** [CMakeFiles/Makefile2:708: CMakeFiles/test_subscriber_cpp.dir/all] Error 2
02:27:08 make: *** [Makefile:141: all] Error 2
```

The latest changes to that test happened on https://github.com/ros2/system_tests/pull/481, and we've had nightlies succeeding after that. So it doesn't seem to me that the failure has been introduced by changes in this repository. There may actually be an external reason for the failure and it just happens to always manifest when this package is being built due to timing.

---

https://github.com/osrf/buildfarmer/issues/224

**Comment by clalancette** [comment]
Looking at https://github.com/ros2/system_tests/blob/master/test_communication/test/test_subscriber.cpp , it looks like it template-generates a function for all possible types.  That is likely what is causing the OOM error sometimes.  One easy way to fix this would be to put that templated function in a header file, then generate a separate binary per type.  Each individual compilation unit would then be a lot smaller.

**Comment by clalancette** [comment]
I haven't seen this particular failure in a while now, so maybe we reduced things enough?  Unclear, but I'm going to close this for now and we can open a follow-up or a new one as necessary.
