### ISSUE TITLE
`test_quality_of_service` test fails with `rmw_connextdds`

### ISSUE THREAD

**Issue by Blast545** [ros2/system_tests#502]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Jammy
- Installation type:
  - Source, buildfarm
- Version or commit hash:
  - `main`
- DDS implementation:
  - Connext DDS

#### Steps to reproduce issue
Run a linux job on the debug ci.ros2.org buildfarm

#### Expected behavior
All test pass.

#### Actual behavior
This one fails: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2293/testReport/junit/(root)/projectroot/test_best_available__rmw_connextdds/
It seems to be segfaulting.

#### Additional information
Reference job before the failure: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2286/ 
First case with the error:  https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2287/
Introduced with: https://github.com/ros2/system_tests/pull/501

Error log: 

```
4: [----------] 4 tests from QosRclcppTestFixture__rmw_connextdds^M
4: [ RUN      ] QosRclcppTestFixture__rmw_connextdds.test_best_available_policies_subscription^M
4: [INFO] [1651661969.753951576] [publisher]: created publisher publisher /test_best_available_subscription^M
4: ^M
4: test_best_available__rmw_connextdds: /home/jenkins-agent/workspace/nightly_linux_debug/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_impl.cpp:289: rmw_time_t dds_durat\
ion_to_rmw_time(const DDS_Duration_t&): Assertion `duration.sec > 0' failed.^M
4: -- run_test.py: return code -6^M
4: -- run_test.py: generate result file '/home/jenkins-agent/workspace/nightly_linux_debug/ws/build/test_quality_of_service/test_results/test_quality_of_service/test_best_available__rmw_co\
nnextdds.gtest.xml' with failed test^M
4: -- run_test.py: verify result file '/home/jenkins-agent/workspace/nightly_linux_debug/ws/build/test_quality_of_service/test_results/test_quality_of_service/test_best_available__rmw_conn\
extdds.gtest.xml'^M
1/1 Test #4: test_best_available__rmw_connextdds ...***Failed    0.32 sec^M
^M
0% tests passed^[[0;0m, ^[[0;31m1 tests failed^[[0;0m out of 1^M

```

**Comment by Blast545** [comment]
The line throwing the assertion is:

https://github.com/ros2/rmw_connextdds/blob/master/rmw_connextdds_common/src/common/rmw_impl.cpp#L289

`rmw_connext` is not able current to manage the default values set on `rclcpp`
https://github.com/ros2/rmw_connextdds/blob/master/rmw_connextdds_common/src/common/rmw_impl.cpp#L529-L534

**Comment by mjeronimo** [comment]
I submitted a PR here: https://github.com/ros2/rmw_connextdds/pull/88
